package Vista.Ventanas;


import Controladores.ControladorRegistroDeReserva;
import java.awt.Font;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.text.Document;
import Modelo.*;
import Vista.Interfaces.InterfazRegistro;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lenovo
 */
public class VistaRegistroDeReserva extends javax.swing.JFrame implements InterfazRegistro{

    imagenFondo fondo = new imagenFondo();
    
    
    public VistaRegistroDeReserva() {
        this.setContentPane(fondo);
        initComponents();
        btnRegistrarse.setActionCommand(REGISTRARSE);
        btnAtrasRegistro.setActionCommand(ATRAS);
        rbtnMostrarContraseña.setActionCommand(mostrarContraseña);
        this.ocultarLbls();
        this.lblResultadoRegistro.setVisible(false);
        this.setResizable(false);
    }
    
    private class imagenFondo extends JPanel
    {
        private Image imagen;
        
        public void paint(Graphics g)
        {
            imagen = new ImageIcon(getClass().getResource("/imagenesproyecto/fondoLogin.jpg")).getImage();
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);
            setOpaque(false);
            super.paint(g);
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel1 = new imagenFondo();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreYApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtUsuarioRegistro = new javax.swing.JTextField();
        lblContraseñaRegistro = new javax.swing.JLabel();
        btnRegistrarse = new javax.swing.JButton();
        btnAtrasRegistro = new javax.swing.JButton();
        rbtnMostrarContraseña = new javax.swing.JRadioButton();
        pfContraseña = new javax.swing.JPasswordField();
        lblRelleneCamposFaltantes = new javax.swing.JLabel();
        lblResultadoRegistro = new javax.swing.JLabel();
        lblast1 = new javax.swing.JLabel();
        lblast2 = new javax.swing.JLabel();
        lblast3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(707, 610));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("REGISTRO DE RESERVA");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Nombre y Apellido");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Usuario");

        txtUsuarioRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioRegistroActionPerformed(evt);
            }
        });

        lblContraseñaRegistro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblContraseñaRegistro.setText("Contraseña");

        btnRegistrarse.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegistrarse.setText("Registrarse");

        btnAtrasRegistro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAtrasRegistro.setText("Atrás");

        rbtnMostrarContraseña.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rbtnMostrarContraseña.setText("Mostrar contraseña");

        lblRelleneCamposFaltantes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRelleneCamposFaltantes.setForeground(new java.awt.Color(255, 51, 51));
        lblRelleneCamposFaltantes.setText("¡rellene los campos faltantes!(*)");

        lblResultadoRegistro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblResultadoRegistro.setForeground(new java.awt.Color(255, 51, 51));
        lblResultadoRegistro.setText("¡el usuario ya existe!");

        lblast1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblast1.setForeground(new java.awt.Color(255, 51, 51));
        lblast1.setText("*");

        lblast2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblast2.setForeground(new java.awt.Color(255, 51, 51));
        lblast2.setText("*");

        lblast3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblast3.setForeground(new java.awt.Color(255, 51, 51));
        lblast3.setText("*");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesproyecto/REGISTRO DE USUARIO.JPG"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblast1)
                            .addComponent(lblast2)
                            .addComponent(lblast3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(786, 786, 786)
                                .addComponent(jLabel5))
                            .addComponent(txtNombreYApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblResultadoRegistro))
                            .addComponent(lblContraseñaRegistro)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(pfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnMostrarContraseña))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnRegistrarse)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblRelleneCamposFaltantes))
                            .addComponent(btnAtrasRegistro)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jLabel5)
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2)
                        .addGap(137, 137, 137))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreYApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblast1))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtUsuarioRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblResultadoRegistro))
                    .addComponent(lblast2))
                .addGap(18, 18, 18)
                .addComponent(lblContraseñaRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblast3)
                    .addComponent(rbtnMostrarContraseña))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarse)
                    .addComponent(lblRelleneCamposFaltantes))
                .addGap(18, 18, 18)
                .addComponent(btnAtrasRegistro)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        btnRegistrarse.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioRegistroActionPerformed
    }//GEN-LAST:event_txtUsuarioRegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroDeReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroDeReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroDeReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroDeReserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                /**/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAtrasRegistro;
    public javax.swing.JButton btnRegistrarse;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton jToggleButton1;
    public javax.swing.JLabel lblContraseñaRegistro;
    public javax.swing.JLabel lblRelleneCamposFaltantes;
    public javax.swing.JLabel lblResultadoRegistro;
    public javax.swing.JLabel lblast1;
    public javax.swing.JLabel lblast2;
    public javax.swing.JLabel lblast3;
    public javax.swing.JPasswordField pfContraseña;
    public javax.swing.JRadioButton rbtnMostrarContraseña;
    public javax.swing.JTextField txtNombreYApellido;
    public javax.swing.JTextField txtUsuarioRegistro;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setControlador(ControladorRegistroDeReserva c) {
        btnAtrasRegistro.addActionListener((ActionListener) c);
        btnRegistrarse.addActionListener((ActionListener) c);
        rbtnMostrarContraseña.addActionListener((ActionListener) c);
    }

    @Override
    public void arranca() {
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    @Override
    public void ocultarLbls() {
        this.lblRelleneCamposFaltantes.setVisible(false);
        this.lblast1.setVisible(false);
        this.lblast2.setVisible(false);
        this.lblast3.setVisible(false);
    }

    @Override
    public boolean faltanLlenarDatos() {
        boolean falta = false;
        if(this.txtNombreYApellido.getText().isEmpty() || 
                this.txtUsuarioRegistro.getText().isEmpty()
                || this.pfContraseña.getText().isEmpty())
        {
            falta = true;
        }
        
        return falta;
    }

    @Override
    public Cliente devolverCliente() {
        String nombreYApellido = txtNombreYApellido.getText();
        String usuario = txtUsuarioRegistro.getText();
        String contraseña = pfContraseña.getText();
        Cliente cliente = new Cliente(nombreYApellido,usuario,contraseña);
        return cliente;
    }
}
